#!/usr/bin/env python3
"""Generate the sandbox's local env files ONCE, with fresh random secrets.

    app-stack/.env            DB name/user/password/port for docker compose
    app/backend/.env          backend Settings (DATABASE_URL, JWT secret, admin creds, ...)
    app/frontend/.env.local   Vite env (API base, mock off)

Existing files are never overwritten (delete one to regenerate it). Nothing is
printed except file names — the values stay in the gitignored files.
Stdlib only; any python3 works.
"""
from __future__ import annotations

import os
import pathlib
import secrets

STACK = pathlib.Path(__file__).resolve().parent.parent
ROOT = STACK.parent
STACK_ENV = STACK / ".env"
BACKEND_ENV = ROOT / "app" / "backend" / ".env"
FRONTEND_ENV = ROOT / "app" / "frontend" / ".env.local"


def _write(path: pathlib.Path, body: str) -> None:
    old = os.umask(0o077)
    try:
        path.write_text(body, encoding="utf-8")
    finally:
        os.umask(old)
    print(f"generated {path.relative_to(ROOT)}")


def _read(path: pathlib.Path) -> dict:
    out = {}
    for line in path.read_text(encoding="utf-8").splitlines():
        if "=" in line and not line.lstrip().startswith("#"):
            k, v = line.split("=", 1)
            out[k.strip()] = v.strip()
    return out


def main() -> None:
    if not STACK_ENV.exists():
        _write(STACK_ENV, (
            "# matrix-app local stack — generated, gitignored. Never commit.\n"
            "APP_DB_NAME=matrix\n"
            "APP_DB_USER=postgres\n"
            f"APP_DB_PASSWORD={secrets.token_urlsafe(24)}\n"
            "APP_DB_PORT=54330\n"
        ))
    stack = _read(STACK_ENV)

    if not BACKEND_ENV.exists():
        _write(BACKEND_ENV, f"""# Sandbox backend config — LOCAL ONLY. Generated by app-stack/bootstrap/gen_env.py; gitignored.
# Fresh random secrets; nothing here is shared with any real deployment.
APP_NAME=Matrix (local sandbox)
API_PREFIX=/api
DEBUG=false
LOG_LEVEL=INFO

# Secure mode: real (random) secrets, so the insecure-dev escape hatch stays OFF.
ALLOW_INSECURE_DEFAULTS=false
ALLOW_ANON_DEMO_USER=false
# Local convenience only: serves /api/docs + /api/openapi.json on localhost.
ENABLE_DOCS=true

CORS_ORIGINS=http://localhost:5173,http://127.0.0.1:5173
CORS_ALLOW_LOCALHOST=false

# Local Postgres from app-stack (compose project matrix-app), loopback only.
DATABASE_URL=postgresql+asyncpg://{stack['APP_DB_USER']}:{stack['APP_DB_PASSWORD']}@127.0.0.1:{stack['APP_DB_PORT']}/{stack['APP_DB_NAME']}

# HS256 signing key for user + platform-admin JWTs (app-native auth; no hosted Supabase Auth).
SUPABASE_JWT_SECRET={secrets.token_hex(32)}
SUPABASE_JWT_AUDIENCE=authenticated
PASSWORDLESS_DEMO_CODES=

# Storage: local Supabase-Storage-compatible stub (app-stack/storage-stub.mjs) on loopback.
SUPABASE_PROJECT_URL=http://127.0.0.1:54331
SUPABASE_SERVICE_ROLE_KEY={secrets.token_urlsafe(32)}
SUPABASE_STORAGE_BUCKET=site-files

# Email: Resend left unset -> rows accumulate in notification_outbox (nothing is sent).
RESEND_API_KEY=

# Platform admin portal (/admin). Login mints a 30-min admin JWT; the
# X-Platform-Admin-Key header must carry THAT JWT (PLATFORM_ADMIN_TOKEN is no longer
# accepted as a static key since upstream #312, kept here for completeness).
PLATFORM_ADMIN_EMAIL=platform-admin@example.com
PLATFORM_ADMIN_PASSWORD={secrets.token_urlsafe(18)}
PLATFORM_ADMIN_TOKEN={secrets.token_urlsafe(32)}
""")

    if not FRONTEND_ENV.exists():
        _write(FRONTEND_ENV, """# Sandbox frontend config — LOCAL ONLY (gitignored via app/.gitignore: .env.local).
# The API base INCLUDES /api (httpAdapter + supabaseAuth append /auth/..., /tenancy/...).
VITE_API_BASE_URL=http://localhost:8000/api
VITE_USE_MOCK=false
VITE_MOCK_FAIL_RATE=0
VITE_API_TIMEOUT_MS=20000
# Same value production builds with (frontend/.env.production).
VITE_FEATURE_RENT_V2=true
# VITE_SUPABASE_URL / VITE_SUPABASE_ANON_KEY intentionally unset: the frontend only
# uses them for the hosted `resolve-maps-url` Edge Function (short Google Maps links).
# See app-stack/EXTERNAL-DEPS.md.
""")


if __name__ == "__main__":
    main()
