#!/usr/bin/env python3
"""Render docs/templates/MATRIX-BD-TEMPLATES.md from the *.template.json files (do not edit the .md by hand)."""
import json
import os

HERE = os.path.dirname(os.path.abspath(__file__))
OUT = os.path.join(os.path.dirname(os.path.dirname(HERE)), "docs", "templates", "MATRIX-BD-TEMPLATES.md")
ORDER = ["bd", "legal", "finance_ca", "design", "project_excellence", "project", "nso", "launch_approval", "financial_closure"]


def roles(sub):
    r = " / ".join(sub["roles"])
    if sub.get("module"):
        r += f" *(from {sub['module']})*"
    if sub.get("restricted_to"):
        who = ", ".join(sub.get("restrict_roles", sub["roles"]))
        r += f" — {who}: **{sub['restricted_to']}** only"
    return r


def tier(a):
    s = a["role"] + (f" *(from {a['module']})*" if a.get("module") else "")
    if a.get("label"):
        s += f" “{a['label']}”"
    return s + " [" + ", ".join(a.get("actions", [])) + "]"


def gate(g):
    if not g:
        return "—"
    return f" {g['match'].upper()} ".join(f"`{c['source']}` reached `{c['outcome']}`" for c in g["conditions"])


md = ["# Matrix-bd built-ins as manifest templates — reference",
      "",
      "_Generated by `templates/matrix-bd/render_docs.py` from the `*.template.json` files. Overview and rationale: [`README.md`](README.md)._",
      ""]
for k in ORDER:
    t = json.load(open(os.path.join(HERE, f"{k}.template.json"), encoding="utf-8"))
    m, s = t["module"], t["summary"]
    md += [f"## {m['name']} — `{t['template']['key']}@{t['template']['version']}`", "",
           f"Source: Matrix-bd `{t['template']['source']['module']}` @ `{t['template']['source']['commit'][:7]}` · members: {', '.join(m['members'])}"
           f" · delegation: {'on' if m['delegation'] else 'off'} · separation of duties: {'on' if m.get('separation_of_duties', True) else 'off'}", "",
           f"**Entry gate:** {gate(m['entry_gate'])}  ",
           f"**Exit outcomes:** complete → `{m['exit']['on_complete']}`" + (f", reject → `{m['exit']['on_reject']}`" if m['exit'].get('on_reject') else " (no terminal reject)") + "  ",
           f"**Approval tiers used:** {', '.join(s['approval_tiers']) or '—'}  ",
           f"**Requires modules:** {', '.join(t['requires']['modules']) or '—'}", "",
           "| # | Stage | Submit | Approval tiers (actions) | Fields (submit / approver) | Reaches | Stage gate / send-back |",
           "|---|---|---|---|---|---|---|"]
    for i, st in enumerate(s["stages"], 1):
        sg = []
        if st.get("gate"):
            sg.append("gate: " + gate(st["gate"]))
        if st.get("send_back_to"):
            sg.append("send back → " + ", ".join(st["send_back_to"]))
        fields = ", ".join(f"`{f}`" for f in st["fields"]) or "—"
        if st["approval_fields"]:
            fields += " / " + ", ".join(f"`{f}`" for f in st["approval_fields"])
        md.append(f"| {i} | {st['name']} (`{st['key']}`) | {roles(st['submit'])} | {'<br>'.join(tier(a) for a in st['approvals']) or '—'} | {fields} | `{st['outcome']}` | {'; '.join(sg) or '—'} |")
    md += ["", "**Required adapter hooks:**" + (" none — fully expressed by the manifest." if not t["adapter_hooks"] else ""), ""]
    if t["adapter_hooks"]:
        md += ["| Hook | Purpose | Why not generic | Generic candidate | Matrix-bd source |", "|---|---|---|---|---|"]
        md += [f"| `{h['hook']}` | {h['purpose']} | {h['why_not_generic']} | {h.get('generic_candidate', '—')} | `{h['matrix_bd_source']}` |" for h in t["adapter_hooks"]]
        md.append("")
    md += ["| Generic (any workspace) | Matrix-bd-specific |", "|---|---|"]
    g, x = t["behaviour"]["generic"], t["behaviour"]["matrix_bd_specific"]
    for i in range(max(len(g), len(x))):
        md.append(f"| {g[i] if i < len(g) else ''} | {x[i] if i < len(x) else ''} |")
    if t.get("renamed_fields"):
        md += ["", "Renamed fields (brand-free keys): " + ", ".join(f"`{a}` → `{b}`" for a, b in t["renamed_fields"].items())]
    md.append("")
open(OUT, "w", encoding="utf-8").write("\n".join(md))
print("wrote", OUT)
